# Generated by Django 4.2.6 on 2023-10-15 02:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("care", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="centerrating",
            name="text",
            field=models.TextField(blank=True, verbose_name="Отзыв"),
        ),
    ]
