# Generated by Django 4.2.6 on 2023-10-14 13:04

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.TextField(blank=True, verbose_name="Номер телефона")),
                ("address", models.TextField(blank=True, verbose_name="Адрес")),
            ],
        ),
        migrations.AddField(
            model_name="customuser",
            name="date_of_birth",
            field=models.DateField(
                default=django.utils.timezone.now,
                verbose_name="Дата рождения пользователя",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="gender",
            field=models.CharField(
                choices=[("MALE", "Мужской"), ("FEMALE", "Женский")],
                max_length=6,
                null=True,
                verbose_name="Пол пользователя",
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="middle_name",
            field=models.TextField(default="", verbose_name="Отчество пользователя"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                max_length=254, unique=True, verbose_name="Электронная почта"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="first_name",
            field=models.TextField(default="", verbose_name="Имя пользователя"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="last_name",
            field=models.TextField(default="", verbose_name="Фамилия пользователя"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="contact_data",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="users.contactdata",
            ),
        ),
    ]
