# Generated by Django 4.2.6 on 2023-10-14 14:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_contactdata_customuser_date_of_birth_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactdata",
            name="city",
            field=models.TextField(blank=True, verbose_name="Город"),
        ),
    ]
