# Generated by Django 4.2.6 on 2023-10-15 11:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_contactdata_city"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contactdata",
            options={
                "verbose_name": "Контактные данные",
                "verbose_name_plural": "Контактные данные",
            },
        ),
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
